/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminContentSettings {
  'masterAdminKey' : [] | [string],
  'background' : [] | [ExternalBlob],
  'logo' : [] | [ExternalBlob],
  'termsAndConditions' : string,
}
export interface BinderTheme {
  'pageBackground' : string,
  'coverColor' : string,
  'coverTexture' : [] | [string],
  'borderStyle' : string,
  'accentColor' : string,
  'backgroundPattern' : [] | [string],
  'cardFrameStyle' : string,
  'textColor' : string,
}
export interface BinderView {
  'id' : string,
  'theme' : BinderTheme,
  'created' : Time,
  'cards' : Array<Photocard>,
  'name' : string,
}
export type CardCondition = { 'played' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'mint' : null } |
  { 'none' : null } |
  { 'nearMint' : null };
export interface CardPosition { 'page' : bigint, 'slot' : bigint }
export type CardRarity = { 'ultraRare' : null } |
  { 'legendary' : null } |
  { 'none' : null } |
  { 'rare' : null } |
  { 'common' : null };
export type ExternalBlob = Uint8Array;
export interface Photocard {
  'id' : string,
  'created' : Time,
  'name' : string,
  'quantity' : bigint,
  'rarity' : CardRarity,
  'image' : ExternalBlob,
  'position' : CardPosition,
  'condition' : CardCondition,
}
export type SubscriptionStatus = { 'pro' : null } |
  { 'free' : null };
export type Time = bigint;
export interface UserAnalytics {
  'binderCount' : bigint,
  'principal' : Principal,
  'joinDate' : Time,
  'email' : [] | [string],
  'subscriptionStatus' : SubscriptionStatus,
  'cardCount' : bigint,
}
export interface UserProfile {
  'displayName' : [] | [string],
  'name' : string,
  'email' : [] | [string],
  'avatarUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLayoutPreset' : ActorMethod<[string], undefined>,
  'addPhotocard' : ActorMethod<
    [
      string,
      string,
      ExternalBlob,
      CardPosition,
      bigint,
      CardRarity,
      CardCondition,
    ],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBinder' : ActorMethod<[string, BinderTheme], string>,
  'deleteBinder' : ActorMethod<[string], undefined>,
  'deletePhotocard' : ActorMethod<[string, string], undefined>,
  'getAdminContentSettings' : ActorMethod<[], AdminContentSettings>,
  'getAllUsers' : ActorMethod<[], Array<UserAnalytics>>,
  'getBinders' : ActorMethod<[], Array<BinderView>>,
  'getBindersByUser' : ActorMethod<[Principal], Array<BinderView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultLayout' : ActorMethod<[], string>,
  'getFilteredUsers' : ActorMethod<[string], Array<UserAnalytics>>,
  'getLayoutPresets' : ActorMethod<[], Array<string>>,
  'getMasterAdminKey' : ActorMethod<[], [] | [string]>,
  'getSubscriptionStatus' : ActorMethod<[], SubscriptionStatus>,
  'getUserLayout' : ActorMethod<[Principal], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeLayoutPreset' : ActorMethod<[string], undefined>,
  'reorderCards' : ActorMethod<[string, Array<string>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDefaultLayout' : ActorMethod<[string], undefined>,
  'updateAdminContentSettings' : ActorMethod<[AdminContentSettings], undefined>,
  'updateBinderTheme' : ActorMethod<[string, BinderTheme], undefined>,
  'updateMasterAdminKey' : ActorMethod<[string], undefined>,
  'updatePhotocard' : ActorMethod<
    [
      string,
      string,
      string,
      ExternalBlob,
      CardPosition,
      bigint,
      CardRarity,
      CardCondition,
    ],
    undefined
  >,
  'updateSubscriptionStatus' : ActorMethod<
    [Principal, SubscriptionStatus],
    undefined
  >,
  'updateUserLayout' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];