/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CardPosition = IDL.Record({ 'page' : IDL.Nat, 'slot' : IDL.Nat });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BinderTheme = IDL.Record({
  'pageBackground' : IDL.Text,
  'coverColor' : IDL.Text,
  'coverTexture' : IDL.Opt(IDL.Text),
  'borderStyle' : IDL.Text,
  'accentColor' : IDL.Text,
  'backgroundPattern' : IDL.Opt(IDL.Text),
  'cardFrameStyle' : IDL.Text,
  'textColor' : IDL.Text,
});
export const Time = IDL.Int;
export const Photocard = IDL.Record({
  'id' : IDL.Text,
  'created' : Time,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'image' : ExternalBlob,
  'position' : CardPosition,
});
export const BinderView = IDL.Record({
  'id' : IDL.Text,
  'theme' : BinderTheme,
  'created' : Time,
  'cards' : IDL.Vec(Photocard),
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const SubscriptionStatus = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPhotocard' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, CardPosition, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBinder' : IDL.Func([IDL.Text, BinderTheme], [IDL.Text], []),
  'deleteBinder' : IDL.Func([IDL.Text], [], []),
  'getBinders' : IDL.Func([], [IDL.Vec(BinderView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderCards' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBinderTheme' : IDL.Func([IDL.Text, BinderTheme], [], []),
  'updateSubscriptionStatus' : IDL.Func(
      [IDL.Principal, SubscriptionStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CardPosition = IDL.Record({ 'page' : IDL.Nat, 'slot' : IDL.Nat });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BinderTheme = IDL.Record({
    'pageBackground' : IDL.Text,
    'coverColor' : IDL.Text,
    'coverTexture' : IDL.Opt(IDL.Text),
    'borderStyle' : IDL.Text,
    'accentColor' : IDL.Text,
    'backgroundPattern' : IDL.Opt(IDL.Text),
    'cardFrameStyle' : IDL.Text,
    'textColor' : IDL.Text,
  });
  const Time = IDL.Int;
  const Photocard = IDL.Record({
    'id' : IDL.Text,
    'created' : Time,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'image' : ExternalBlob,
    'position' : CardPosition,
  });
  const BinderView = IDL.Record({
    'id' : IDL.Text,
    'theme' : BinderTheme,
    'created' : Time,
    'cards' : IDL.Vec(Photocard),
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const SubscriptionStatus = IDL.Variant({
    'pro' : IDL.Null,
    'free' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPhotocard' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, CardPosition, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBinder' : IDL.Func([IDL.Text, BinderTheme], [IDL.Text], []),
    'deleteBinder' : IDL.Func([IDL.Text], [], []),
    'getBinders' : IDL.Func([], [IDL.Vec(BinderView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderCards' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBinderTheme' : IDL.Func([IDL.Text, BinderTheme], [], []),
    'updateSubscriptionStatus' : IDL.Func(
        [IDL.Principal, SubscriptionStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };