/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CardPosition = IDL.Record({ 'page' : IDL.Nat, 'slot' : IDL.Nat });
export const CardRarity = IDL.Variant({
  'ultraRare' : IDL.Null,
  'legendary' : IDL.Null,
  'none' : IDL.Null,
  'rare' : IDL.Null,
  'common' : IDL.Null,
});
export const CardCondition = IDL.Variant({
  'played' : IDL.Null,
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'mint' : IDL.Null,
  'none' : IDL.Null,
  'nearMint' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BinderTheme = IDL.Record({
  'pageBackground' : IDL.Text,
  'coverColor' : IDL.Text,
  'coverTexture' : IDL.Opt(IDL.Text),
  'borderStyle' : IDL.Text,
  'accentColor' : IDL.Text,
  'backgroundPattern' : IDL.Opt(IDL.Text),
  'cardFrameStyle' : IDL.Text,
  'textColor' : IDL.Text,
});
export const AdminContentSettings = IDL.Record({
  'masterAdminKey' : IDL.Opt(IDL.Text),
  'background' : IDL.Opt(ExternalBlob),
  'logo' : IDL.Opt(ExternalBlob),
  'termsAndConditions' : IDL.Text,
});
export const Time = IDL.Int;
export const SubscriptionStatus = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
});
export const UserAnalytics = IDL.Record({
  'binderCount' : IDL.Nat,
  'principal' : IDL.Principal,
  'joinDate' : Time,
  'email' : IDL.Opt(IDL.Text),
  'subscriptionStatus' : SubscriptionStatus,
  'cardCount' : IDL.Nat,
});
export const Photocard = IDL.Record({
  'id' : IDL.Text,
  'created' : Time,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'rarity' : CardRarity,
  'image' : ExternalBlob,
  'position' : CardPosition,
  'condition' : CardCondition,
});
export const BinderView = IDL.Record({
  'id' : IDL.Text,
  'theme' : BinderTheme,
  'created' : Time,
  'cards' : IDL.Vec(Photocard),
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLayoutPreset' : IDL.Func([IDL.Text], [], []),
  'addPhotocard' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        CardPosition,
        IDL.Nat,
        CardRarity,
        CardCondition,
      ],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBinder' : IDL.Func([IDL.Text, BinderTheme], [IDL.Text], []),
  'deleteBinder' : IDL.Func([IDL.Text], [], []),
  'deletePhotocard' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAdminContentSettings' : IDL.Func([], [AdminContentSettings], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserAnalytics)], ['query']),
  'getBinders' : IDL.Func([], [IDL.Vec(BinderView)], ['query']),
  'getBindersByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BinderView)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefaultLayout' : IDL.Func([], [IDL.Text], ['query']),
  'getFilteredUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserAnalytics)],
      ['query'],
    ),
  'getLayoutPresets' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMasterAdminKey' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
  'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'getUserLayout' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeLayoutPreset' : IDL.Func([IDL.Text], [], []),
  'reorderCards' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDefaultLayout' : IDL.Func([IDL.Text], [], []),
  'updateAdminContentSettings' : IDL.Func([AdminContentSettings], [], []),
  'updateBinderTheme' : IDL.Func([IDL.Text, BinderTheme], [], []),
  'updateMasterAdminKey' : IDL.Func([IDL.Text], [], []),
  'updatePhotocard' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        CardPosition,
        IDL.Nat,
        CardRarity,
        CardCondition,
      ],
      [],
      [],
    ),
  'updateSubscriptionStatus' : IDL.Func(
      [IDL.Principal, SubscriptionStatus],
      [],
      [],
    ),
  'updateUserLayout' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CardPosition = IDL.Record({ 'page' : IDL.Nat, 'slot' : IDL.Nat });
  const CardRarity = IDL.Variant({
    'ultraRare' : IDL.Null,
    'legendary' : IDL.Null,
    'none' : IDL.Null,
    'rare' : IDL.Null,
    'common' : IDL.Null,
  });
  const CardCondition = IDL.Variant({
    'played' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'mint' : IDL.Null,
    'none' : IDL.Null,
    'nearMint' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BinderTheme = IDL.Record({
    'pageBackground' : IDL.Text,
    'coverColor' : IDL.Text,
    'coverTexture' : IDL.Opt(IDL.Text),
    'borderStyle' : IDL.Text,
    'accentColor' : IDL.Text,
    'backgroundPattern' : IDL.Opt(IDL.Text),
    'cardFrameStyle' : IDL.Text,
    'textColor' : IDL.Text,
  });
  const AdminContentSettings = IDL.Record({
    'masterAdminKey' : IDL.Opt(IDL.Text),
    'background' : IDL.Opt(ExternalBlob),
    'logo' : IDL.Opt(ExternalBlob),
    'termsAndConditions' : IDL.Text,
  });
  const Time = IDL.Int;
  const SubscriptionStatus = IDL.Variant({
    'pro' : IDL.Null,
    'free' : IDL.Null,
  });
  const UserAnalytics = IDL.Record({
    'binderCount' : IDL.Nat,
    'principal' : IDL.Principal,
    'joinDate' : Time,
    'email' : IDL.Opt(IDL.Text),
    'subscriptionStatus' : SubscriptionStatus,
    'cardCount' : IDL.Nat,
  });
  const Photocard = IDL.Record({
    'id' : IDL.Text,
    'created' : Time,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'rarity' : CardRarity,
    'image' : ExternalBlob,
    'position' : CardPosition,
    'condition' : CardCondition,
  });
  const BinderView = IDL.Record({
    'id' : IDL.Text,
    'theme' : BinderTheme,
    'created' : Time,
    'cards' : IDL.Vec(Photocard),
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLayoutPreset' : IDL.Func([IDL.Text], [], []),
    'addPhotocard' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          CardPosition,
          IDL.Nat,
          CardRarity,
          CardCondition,
        ],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBinder' : IDL.Func([IDL.Text, BinderTheme], [IDL.Text], []),
    'deleteBinder' : IDL.Func([IDL.Text], [], []),
    'deletePhotocard' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAdminContentSettings' : IDL.Func([], [AdminContentSettings], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserAnalytics)], ['query']),
    'getBinders' : IDL.Func([], [IDL.Vec(BinderView)], ['query']),
    'getBindersByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BinderView)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefaultLayout' : IDL.Func([], [IDL.Text], ['query']),
    'getFilteredUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserAnalytics)],
        ['query'],
      ),
    'getLayoutPresets' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMasterAdminKey' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
    'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'getUserLayout' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeLayoutPreset' : IDL.Func([IDL.Text], [], []),
    'reorderCards' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDefaultLayout' : IDL.Func([IDL.Text], [], []),
    'updateAdminContentSettings' : IDL.Func([AdminContentSettings], [], []),
    'updateBinderTheme' : IDL.Func([IDL.Text, BinderTheme], [], []),
    'updateMasterAdminKey' : IDL.Func([IDL.Text], [], []),
    'updatePhotocard' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          CardPosition,
          IDL.Nat,
          CardRarity,
          CardCondition,
        ],
        [],
        [],
      ),
    'updateSubscriptionStatus' : IDL.Func(
        [IDL.Principal, SubscriptionStatus],
        [],
        [],
      ),
    'updateUserLayout' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };